### ISSUE TITLE
You can build, but the code won't run

### ISSUE THREAD

**Issue by dionjwa** [thdk/TS3-projects-references-example#1]
```
/tmp/TS3-projects-references-example ‹es*›$ node project-a/app-a.js 
(node:82579) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/private/tmp/TS3-projects-references-example/project-a/app-a.js:1
import { logProjectName } from '../common';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

If you ` set "type": "module"` then:

```
node project-a/app-a.js
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/private/tmp/TS3-projects-references-example/common' is not supported resolving ES modules, imported from /private/tmp/TS3-projects-references-example/project-a/app-a.js
    at finalizeResolution (internal/modules/esm/resolve.js:254:17)
    at moduleResolve (internal/modules/esm/resolve.js:636:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:726:11)
    at Loader.resolve (internal/modules/esm/loader.js:82:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:226:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///private/tmp/TS3-projects-references-example/common'
}

```

I've been doing this dance for a while now with my own project. Seems so close, yet so far.

**Comment by theocerutti** [comment]
Did you manage to make it works?
